[2025-02-14T22:40:16.940+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-14T22:40:12.274296+00:00 [queued]>
[2025-02-14T22:40:16.953+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-14T22:40:12.274296+00:00 [queued]>
[2025-02-14T22:40:16.954+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-14T22:40:16.971+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): get_location_dict> on 2025-02-14 22:40:12.274296+00:00
[2025-02-14T22:40:16.982+0000] {standard_task_runner.py:57} INFO - Started process 186 to run task
[2025-02-14T22:40:17.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'get_location_dict', 'manual__2025-02-14T22:40:12.274296+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_dag.py', '--cfg-path', '/tmp/tmpjerio5sx']
[2025-02-14T22:40:17.006+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask get_location_dict
[2025-02-14T22:40:17.137+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.get_location_dict manual__2025-02-14T22:40:12.274296+00:00 [running]> on host 2079ceed134c
[2025-02-14T22:40:17.325+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='get_location_dict' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T22:40:12.274296+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T22:40:12.274296+00:00'
[2025-02-14T22:40:17.351+0000] {xcom.py:634} ERROR - keys must be str, int, float, bool or None, not tuple. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-02-14T22:40:17.353+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/utils.py", line 24, in get_location_dict
    kwargs['ti'].xcom_push(key="location_dict", value=location_dict)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2377, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 237, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: keys must be str, int, float, bool or None, not tuple
[2025-02-14T22:40:17.376+0000] {taskinstance.py:1368} INFO - Marking task as FAILED. dag_id=weather_data_ETL, task_id=get_location_dict, execution_date=20250214T224012, start_date=20250214T224016, end_date=20250214T224017
[2025-02-14T22:40:17.399+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task get_location_dict (keys must be str, int, float, bool or None, not tuple; 186)
[2025-02-14T22:40:17.420+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2025-02-14T22:40:17.463+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
