[2025-02-15T02:08:09.766+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.export_daily_forecast manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T02:08:09.781+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.export_daily_forecast manual__2025-02-15T00:56:13.638531+00:00 [queued]>
[2025-02-15T02:08:09.782+0000] {taskinstance.py:1331} INFO - Starting attempt 3 of 3
[2025-02-15T02:08:09.802+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): export_daily_forecast> on 2025-02-15 00:56:13.638531+00:00
[2025-02-15T02:08:09.809+0000] {standard_task_runner.py:57} INFO - Started process 340 to run task
[2025-02-15T02:08:09.814+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'export_daily_forecast', 'manual__2025-02-15T00:56:13.638531+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpaplp8o70']
[2025-02-15T02:08:09.816+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask export_daily_forecast
[2025-02-15T02:08:09.925+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.export_daily_forecast manual__2025-02-15T00:56:13.638531+00:00 [running]> on host cbea98f91475
[2025-02-15T02:08:10.125+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='export_daily_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:56:13.638531+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T00:56:13.638531+00:00'
[2025-02-15T02:08:10.192+0000] {logging_mixin.py:149} INFO - Index(['dt', 'summary', 'pressure', 'humidity', 'dew_point', 'wind_speed',
       'wind_gust', 'clouds', 'pop', 'uvi', 'rain', 'snow', 'main',
       'description', 'min_temp', 'max_temp', 'day_temp', 'day_feels_like',
       'location_id', 'current_weather_id'],
      dtype='object')
[2025-02-15T02:08:10.207+0000] {logging_mixin.py:149} INFO - Error inserting data: column "summary" of relation "hourly_forecast" does not exist
LINE 3:         dt, summary, temp, pressure, humidity, dew_points, w...
                    ^
[2025-02-15T02:08:10.209+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T02:08:10.232+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=export_daily_forecast, execution_date=20250215T005613, start_date=20250215T020809, end_date=20250215T020810
[2025-02-15T02:08:10.270+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T02:08:10.310+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
