[2025-02-15T00:15:45.276+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [queued]>
[2025-02-15T00:15:45.288+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [queued]>
[2025-02-15T00:15:45.289+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 1
[2025-02-15T00:15:45.306+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): export_current_weather> on 2025-02-15 00:15:20.628188+00:00
[2025-02-15T00:15:45.315+0000] {standard_task_runner.py:57} INFO - Started process 1114 to run task
[2025-02-15T00:15:45.318+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_ETL', 'export_current_weather', 'manual__2025-02-15T00:15:20.628188+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpx_3fxufu']
[2025-02-15T00:15:45.321+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask export_current_weather
[2025-02-15T00:15:45.418+0000] {task_command.py:410} INFO - Running <TaskInstance: weather_data_ETL.export_current_weather manual__2025-02-15T00:15:20.628188+00:00 [running]> on host 2079ceed134c
[2025-02-15T00:15:45.720+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='weather_data_ETL' AIRFLOW_CTX_TASK_ID='export_current_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-02-15T00:15:20.628188+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-15T00:15:20.628188+00:00'
[2025-02-15T00:15:45.836+0000] {logging_mixin.py:149} INFO - Error inserting data: relation "current_weather" does not exist
LINE 2:     INSERT INTO current_weather (
                        ^
[2025-02-15T00:15:45.838+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-15T00:15:45.857+0000] {taskinstance.py:1368} INFO - Marking task as SUCCESS. dag_id=weather_data_ETL, task_id=export_current_weather, execution_date=20250215T001520, start_date=20250215T001545, end_date=20250215T001545
[2025-02-15T00:15:45.915+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2025-02-15T00:15:45.959+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
